version: '3'
services:
  product_service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: product_service
    image: product_service:latest
    ports:
      - "8080:8080"
    external_links:
      - "mongo_container:mongo"