version: '3'
services:
  product-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: product-service
    image: product-service:latest
    ports:
      - "8080:8080"
    external_links:
      - "mongodb:mongo"